version: 2.1  

jobs:
  build:
    working_directory: ~/ASDProject
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run: python --version
  test:
    working_directory: ~/ASDProject
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run: python3 main.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
